name: Publish
on:
  push:
    branches:
      - "master"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository ğŸƒğŸ½â€â™‚ï¸
        uses: actions/checkout@v3
      - name: Setup pnpm v7 ğŸ’¡
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Setup Node.js v16.x ğŸ§©
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm
      - name: Install Dependencies ğŸ“¦
        run: pnpm install --frozen-lockfile
      - name: Run Lint, and Test ğŸ§ª
        run: pnpm run lint && pnpm run test
      - name: Biuld the package to dist folder ğŸ› 
        run: pnpm run build
      - name: Create Release Pull Request ğŸ”Œ
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Login to npm registry ğŸ”
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Publish to NPM Registery ğŸ“¨
        if: steps.changesets.outputs.summary != "No changes were made"
        run: pnpm publish


