name: Publish
on:
  push:
    branches:
      - "master"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository ðŸƒðŸ½â€â™‚ï¸
        uses: actions/checkout@v3
      - name: Setup pnpm v7 ðŸ’¡
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Setup Node.js v16.x ðŸ§©
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm
      - name: Install Dependencies ðŸ“¦
        run: pnpm install --frozen-lockfile
      - name: Run Lint, and Test ðŸ§ª
        run: pnpm run lint && pnpm run test
      - name: Biuld the package to dist folder ðŸ› 
        run: pnpm run build
      - name: Create Release Pull Request ðŸ”Œ
        id: changesets
        uses: changesets/action@v1
        with: 
          publish: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          publish: pnpm publish
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}


